[versions]
loom = "1.11.+"

minecraft = "1.20.1"
fabric_loader = "0.17.0"
fabric_api = "0.92.6+1.20.1"
yet_another_config_lib = "3.6.6+1.20.1-fabric"
quilt_json5 = "0.3.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
yet_another_config_lib = { module = "dev.isxander:yet-another-config-lib", version.ref = "yet_another_config_lib" }
quilt_json5 = { module = "org.quiltmc.parsers:json", version.ref = "quilt_json5" }

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }
